import os
import logging
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List

# Import your compiled graph runner directly from your local agentic_rag.py script
from agentic_rag import graph

# Configure basic logging to monitor the terminal
logging.basicConfig(level=logging.INFO)


# We define Request/Response Schemas using Pydantic
class QueryRequest(BaseModel):
    question: str


class QueryResponse(BaseModel):
    node_execution_sequence: List[str]
    final_response: str


# Instantiate FastAPI App
app = FastAPI(
    title="Agentic Fraud Investigation RAG API",
    description="Local API wrapper for LangGraph Corrective RAG pipeline.",
    version="1.0.0",
)


# Root health check endpoint
@app.get("/")
def health_check():
    return {"status": "healthy", "engine": "LangGraph Local Runtime"}


# Main Agent Endpoint
@app.post("/ask", response_model=QueryResponse)
async def ask_agent(payload: QueryRequest):
    """
    Accepts user inquiries, streams them through the LangGraph state machine,
    and returns a structured JSON traceback and response payload.
    """
    if not payload.question.strip():
        raise HTTPException(
            status_code=400, detail="The input query string cannot be empty."
        )

    try:
        # Prepare the input state for your LangGraph instance
        initial_state = {"messages": [{"role": "user", "content": payload.question}]}

        executed_nodes = []
        final_answer = "No response generated by the system."

        logging.info("📥 [API] Request received. Invoking LangGraph runtime stream...")

        # Stream state blocks out of the compiled graph structure
        for chunk in graph.stream(initial_state):
            for node, update in chunk.items():
                executed_nodes.append(node)
                logging.info(f"🕸️ [Graph Node Complete]: {node}")

                # Update final answer text dynamically from state history array
                if "messages" in update and len(update["messages"]) > 0:
                    final_answer = update["messages"][-1].content

        return QueryResponse(
            node_execution_sequence=executed_nodes, final_response=str(final_answer)
        )
    except Exception as e:
        logging.error(f"💥 [API Error]: {str(e)}")
        raise HTTPException(
            status_code=500, detail=f"Graph Execution Exception: {str(e)}"
        )


# Run via standard python terminal hooks
if __name__ == "__main__":
    print("\n🚀 Booting local production server...")
    uvicorn.run("fastapi_rag:app", host="127.0.0.1", port=8000, reload=True)
